final List<String> suggestionSpecialists = [
  'Pediatrician',
  'Allergist',
  'Dermatologist',
  'Ophthalmologist',
  'Obstetrician/gynecologist',
  'Cardiologist',
  'Endocrinologist',
  'Gastroenterologist',
  'Nephrologist',
  'Urologist',
  'Pulmonologist',
  'Otolaryngologist',
  'Neurologist',
  'Psychiatrist',
  'Oncologist',
  'Radiologist',
  'Rheumatologist',
  'General surgeon',
  'Orthopedic surgeon',
  'Cardiac surgeon',
  'Anesthesiologist',
  'Emergency Medicine Specialist',
  'Hematologist',
  'Medical Geneticist',
  'Osteopath',
  'Pathologist',
  'Physiatrist',
  'Plastic Surgeon',
  'Podiatrist',
  'Neonatologist'
];

final List<String> suggestionsCounties = [
  'Mombasa',
  'Kwale',
  'Kilifi',
  'Tana River',
  'Lamu',
  'Taita Taveta',
  'Garissa',
  'Wajir',
  'Mandera',
  'Marsabit',
  'Isiolo',
  'Meru',
  'Tharaka-Nithi',
  'Embu',
  'Kitui',
  'Machakos',
  'Makueni',
  'Nyandarua',
  'Nyeri',
  'Kirinyaga',
  'Muranga',
  'Kiambu',
  'Turkana',
  'West Pokot',
  'Samburu',
  'Trans-Nzoia',
  'Uasin-Gishu',
  'Elgeyo-Marakwet',
  'Nandi',
  'Baringo',
  'Laikipia',
  'Nakuru',
  'Narok',
  'Kajiado',
  'Kericho',
  'Bomet',
  'Kakamega',
  'Vihiga',
  'Bungoma',
  'Busia',
  'Siaya',
  'Siaya',
  'Kisumu',
  'Homa Bay',
  'Migori',
  'Kisii',
  'Nyamira',
  'Nairobi'
];

final List<String> tests = [
  'Xray',
  'CT',
  'MRI',
  'Ultrasound',
  'PET',
  'Blood',
  'DNA',
  'Electrocardiogram'
];
